const ROUTE_MASTER_DOKUMENT_TYPE_PAGE = '/master-pr/dokument-type';

export const LIST_PAGE_MASTER_DOKUMENT_TYPE = `${ROUTE_MASTER_DOKUMENT_TYPE_PAGE}`;
export const CREATE_PAGE_MASTER_DOKUMENT_TYPE = `${ROUTE_MASTER_DOKUMENT_TYPE_PAGE}/create`;
export const EDIT_PAGE_MASTER_DOKUMENT_TYPE = `${ROUTE_MASTER_DOKUMENT_TYPE_PAGE}/update`;
export const DETAIL_PAGE_MASTER_DOKUMENT_TYPE = `${ROUTE_MASTER_DOKUMENT_TYPE_PAGE}/detail`;
