const ROUTE_MASTER_PERMISSION_PAGE = '/user-management/permission';

export const LIST_PAGE_MASTER_PERMISSION = `${ROUTE_MASTER_PERMISSION_PAGE}`;
export const CREATE_PAGE_MASTER_PERMISSION = `${ROUTE_MASTER_PERMISSION_PAGE}/create`;
export const EDIT_PAGE_MASTER_PERMISSION = `${ROUTE_MASTER_PERMISSION_PAGE}/update`;
export const DETAIL_PAGE_MASTER_PERMISSION = `${ROUTE_MASTER_PERMISSION_PAGE}/detail`;
