const ROUTE_APPROVAL_ROUTE_PAGE = '/approval/route';

export const LIST_PAGE_APPROVAL_ROUTE = `${ROUTE_APPROVAL_ROUTE_PAGE}`;
export const CREATE_PAGE_APPROVAL_ROUTE = `${ROUTE_APPROVAL_ROUTE_PAGE}/create`;
export const EDIT_PAGE_APPROVAL_ROUTE = `${ROUTE_APPROVAL_ROUTE_PAGE}/update`;
export const DETAIL_PAGE_APPROVAL_ROUTE = `${ROUTE_APPROVAL_ROUTE_PAGE}/detail`;
