deploy:
  stage: deploy
  tags:
    - majapahit-server-runner
  before_script:
    # Konfigurasi SSH
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H server.majapahit.id >> ~/.ssh/known_hosts
  script:
    # Jalankan perintah deployment di server via SSH
    - ssh mein@server.majapahit.id "
        cd /home/mein/public_html/mein &&
        git pull origin develop &&
        /usr/bin/php8.2 /bin/composer install --optimize-autoloader --no-dev &&
        /usr/bin/php8.2 artisan migrate &&
        /usr/bin/php8.2 artisan cache:clear &&
        /usr/bin/php8.2 artisan config:clear &&
        /usr/bin/php8.2 artisan optimize:clear "
  only:
    - develop
