version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    image: laravel
    container_name: mein
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    networks:
      - utama
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000", "--no-interaction"]

  postgresql-mein:
    container_name: postgresql-mein
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    networks:
      - utama
    expose:
      - '5432'
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  utama:
    external: true
    name: utama