version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: mein
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/mein
    networks:
      - utama

  postgresql-mein:
    container_name: postgresql-mein
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    networks:
      - utama
    expose:
      - '5432'
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    restart: unless-stopped


networks:
  utama:
    driver: bridge
    name: utama
