FROM php:8.2-apache-buster
# Update and setup git
RUN set -eux; \
    apt-get update; \
    apt-get install -y \
    git \
    gpg \
    curl

# Install Composer
RUN set -eux; \
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer;


# Install module
RUN apt-get update -y && apt-get install -y sendmail libpng-dev
RUN apt-get update && \
    apt-get install -y \
        zlib1g-dev \
        zip \
        unzip \
        curl \
        libzip-dev\
        libpq-dev
RUN docker-php-ext-install zip \
gd \
pgsql \
pdo \
pdo_pgsql
# RUN apt-get update && apt-get install -y libldap2-dev && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ && docker-php-ext-install ldap

RUN apt-get update && \
    apt-get install -y \
        libldap2-dev \
        libssl-dev \
    && docker-php-ext-configure ldap \
    && docker-php-ext-install ldap

# Enable module
RUN a2enmod rewrite

# Enable module Header
RUN a2enmod headers

# install Vim
RUN apt-get install -y vim

# Copy Source Code

# Copy existing application directory contents
# COPY ./publikasi /var/www
# Copy existing application directory permissions

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get install -y nodejs

COPY . /var/www/html/mein
WORKDIR /var/www/html/mein
RUN composer update
RUN composer install
RUN npm install
RUN npm run build

RUN apt-get update && apt-get install -y supervisor
RUN mkdir -p /etc/supervisor/conf.d
COPY ./docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

COPY ./.env /var/www/html/mein/
COPY ./docker/info.php /var/www/html/mein/public/
RUN chown -R www-data:www-data /var/www/html/mein
RUN rm /etc/apache2/sites-available/000-default.conf
COPY ./docker/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY ./docker/max_size.ini /usr/local/etc/php/conf.d/max_size.ini
