FROM php:8.2-apache-buster

# Update and install necessary packages
RUN set -eux; \
    apt-get update; \
    apt-get install -y \
    git \
    gpg \
    curl \
    sendmail \
    libpng-dev \
    zlib1g-dev \
    zip \
    unzip \
    libzip-dev \
    libpq-dev \
    libldap2-dev \
    libssl-dev \
    openssl \
    vim

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer;

# PHP Extensions
RUN docker-php-ext-install zip gd pgsql pdo pdo_pgsql pcntl ldap

# Enable Apache modules
RUN a2enmod rewrite headers ssl

# Generate Self-Signed SSL Certificate
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/private/apache-selfsigned.key \
    -out /etc/ssl/certs/apache-selfsigned.crt \
    -subj "/C=US/ST=State/L=City/O=Company/OU=Org/CN=mein.id"

# Copy Source Code
COPY . /var/www/html/mein
WORKDIR /var/www/html/mein

# Composer and NPM setup
RUN composer install
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt-get install -y nodejs
RUN npm install && npm run build

# Supervisor setup
RUN apt-get update && apt-get install -y supervisor
RUN mkdir -p /etc/supervisor/conf.d
COPY ./docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Set permissions
RUN chown -R www-data:www-data /var/www/html/mein

# Apache Configuration
RUN rm /etc/apache2/sites-available/000-default.conf
COPY ./docker/000-default.conf /etc/apache2/sites-available/000-default.conf

# SSL and PHP settings
COPY ./docker/max_size.ini /usr/local/etc/php/conf.d/max_size.ini
RUN a2ensite default-ssl

# Restart Apache
RUN service apache2 restart

# Expose HTTP and HTTPS ports
EXPOSE 80 443
