const ROUTE_MASTER_EXCHANGERATE = '/api/master-pr/exchange-rate';

export const GET_MASTER_EXCHANGERATE = `${ROUTE_MASTER_EXCHANGERATE}/list`;
export const CREATE_MASTER_EXCHANGERATE = `${ROUTE_MASTER_EXCHANGERATE}/create`;
export const EDIT_MASTER_EXCHANGERATE = `${ROUTE_MASTER_EXCHANGERATE}/update`;
export const DETAIL_MASTER_EXCHANGERATE = (id: any) => `${ROUTE_MASTER_EXCHANGERATE}/detail/${id}`;
export const DELET_MASTER_EXCHANGERATE = `${ROUTE_MASTER_EXCHANGERATE}/delete`;
