const ROUTE_MASTER_EXCHANGERATE_PAGE = '/master-pr/exchange-rate';

export const LIST_PAGE_MASTER_EXCHANGERATE = `${ROUTE_MASTER_EXCHANGERATE_PAGE}`;
export const CREATE_PAGE_MASTER_EXCHANGERATE = `${ROUTE_MASTER_EXCHANGERATE_PAGE}/create`;
export const EDIT_PAGE_MASTER_EXCHANGERATE = `${ROUTE_MASTER_EXCHANGERATE_PAGE}/update`;
export const DETAIL_PAGE_MASTER_EXCHANGERATE = `${ROUTE_MASTER_EXCHANGERATE_PAGE}/detail`;
