const ROUTE_MASTER_BANK_KEY_PAGE = '/master/bank-key';

export const LIST_PAGE_MASTER_BANK_KEY = `${ROUTE_MASTER_BANK_KEY_PAGE}`;
export const CREATE_PAGE_MASTER_BANK_KEY = `${ROUTE_MASTER_BANK_KEY_PAGE}/create`;
export const EDIT_PAGE_MASTER_BANK_KEY = `${ROUTE_MASTER_BANK_KEY_PAGE}/update`;
export const DETAIL_PAGE_MASTER_BANK_KEY = `${ROUTE_MASTER_BANK_KEY_PAGE}/detail`;
