const ROUTE_MASTER_ITEM_CATEGORY_PAGE = '/master-pr/item-category';

export const LIST_PAGE_MASTER_ITEM_CATEGORY = `${ROUTE_MASTER_ITEM_CATEGORY_PAGE}`;
export const CREATE_PAGE_MASTER_ITEM_CATEGORY = `${ROUTE_MASTER_ITEM_CATEGORY_PAGE}/create`;
export const EDIT_PAGE_MASTER_ITEM_CATEGORY = `${ROUTE_MASTER_ITEM_CATEGORY_PAGE}/update`;
export const DETAIL_PAGE_MASTER_ITEM_CATEGORY = `${ROUTE_MASTER_ITEM_CATEGORY_PAGE}/detail`;
