const ROUTE_MASTER_MATERIAL_PAGE = '/master/master-material';

export const LIST_PAGE_MASTER_MATERIAL = `${ROUTE_MASTER_MATERIAL_PAGE}`;
export const CREATE_PAGE_MASTER_MATERIAL = `${ROUTE_MASTER_MATERIAL_PAGE}/create`;
export const EDIT_PAGE_MASTER_MATERIAL = `${ROUTE_MASTER_MATERIAL_PAGE}/update`;
export const DETAIL_PAGE_MASTER_MATERIAL = `${ROUTE_MASTER_MATERIAL_PAGE}/detail`;
