const ROUTE_MASTER_DIVISION_PAGE = '/master/division';

export const LIST_PAGE_MASTER_DIVISION = `${ROUTE_MASTER_DIVISION_PAGE}`;
export const CREATE_PAGE_MASTER_DIVISION = `${ROUTE_MASTER_DIVISION_PAGE}/create`;
export const EDIT_PAGE_MASTER_DIVISION = `${ROUTE_MASTER_DIVISION_PAGE}/update`;
export const DETAIL_PAGE_MASTER_DIVISION = `${ROUTE_MASTER_DIVISION_PAGE}/detail`;
