const ROUTE_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY = '/api/master-pr/account-assignment-category';

export const GET_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY = `${ROUTE_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY}/list`;
export const CREATE_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY = `${ROUTE_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY}/create`;
export const EDIT_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY = `${ROUTE_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY}/update`;
export const DETAIL_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY = (id: any) =>
  `${ROUTE_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY}/detail/${id}`;
export const DELET_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY = `${ROUTE_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY}/delete`;
