const ROUTE_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY_PAGE = '/master-pr/account-assignment-category';

export const LIST_PAGE_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY = `${ROUTE_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY_PAGE}`;
export const CREATE_PAGE_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY = `${ROUTE_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY_PAGE}/create`;
export const EDIT_PAGE_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY = `${ROUTE_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY_PAGE}/update`;
export const DETAIL_PAGE_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY = `${ROUTE_MASTER_ACCOUNT_ASSIGNMENT_CATEGORY_PAGE}/detail`;
