const ROUTE_MASTER_BUSINESS_PARTNER = '/api/master/business-parner';

export const GET_MASTER_BUSINESS_PARTNER = `${ROUTE_MASTER_BUSINESS_PARTNER}/list`;
export const CREATE_MASTER_BUSINESS_PARTNER = `${ROUTE_MASTER_BUSINESS_PARTNER}/create`;
export const EDIT_MASTER_BUSINESS_PARTNER = `${ROUTE_MASTER_BUSINESS_PARTNER}/update`;
export const DETAIL_MASTER_BUSINESS_PARTNER = (id: any) =>
  `${ROUTE_MASTER_BUSINESS_PARTNER}/detail/${id}`;
export const DELET_MASTER_BUSINESS_PARTNER = `${ROUTE_MASTER_BUSINESS_PARTNER}/delete`;
