const ROUTE_MASTER_BUSINESS_PARTNER_PAGE = '/master/business-partner';

export const LIST_PAGE_MASTER_BUSINESS_PARTNER = `${ROUTE_MASTER_BUSINESS_PARTNER_PAGE}`;
export const CREATE_PAGE_MASTER_BUSINESS_PARTNER = `${ROUTE_MASTER_BUSINESS_PARTNER_PAGE}/create`;
export const EDIT_PAGE_MASTER_BUSINESS_PARTNER = `${ROUTE_MASTER_BUSINESS_PARTNER_PAGE}/update`;
export const DETAIL_PAGE_MASTER_BUSINESS_PARTNER = `${ROUTE_MASTER_BUSINESS_PARTNER_PAGE}/detail`;
