const ROUTE_MASTER_POSITION_PAGE = '/master/position';

export const LIST_PAGE_MASTER_POSITION = `${ROUTE_MASTER_POSITION_PAGE}`;
export const CREATE_PAGE_MASTER_POSITION = `${ROUTE_MASTER_POSITION_PAGE}/create`;
export const EDIT_PAGE_MASTER_POSITION = `${ROUTE_MASTER_POSITION_PAGE}/update`;
export const DETAIL_PAGE_MASTER_POSITION = `${ROUTE_MASTER_POSITION_PAGE}/detail`;
