const ROUTE_MASTER_VALUATION_TYPE = '/api/master-pr/valuation-type';

export const GET_MASTER_VALUATION_TYPE = `${ROUTE_MASTER_VALUATION_TYPE}/list`;
export const CREATE_MASTER_VALUATION_TYPE = `${ROUTE_MASTER_VALUATION_TYPE}/create`;
export const EDIT_MASTER_VALUATION_TYPE = `${ROUTE_MASTER_VALUATION_TYPE}/update`;
export const DETAIL_MASTER_VALUATION_TYPE = (id: any) =>
  `${ROUTE_MASTER_VALUATION_TYPE}/detail/${id}`;
export const DELET_MASTER_VALUATION_TYPE = `${ROUTE_MASTER_VALUATION_TYPE}/delete`;
