const ROUTE_MASTER_VALUATION_TYPE_PAGE = '/master-pr/valuation-type';

export const LIST_PAGE_MASTER_VALUATION_TYPE = `${ROUTE_MASTER_VALUATION_TYPE_PAGE}`;
export const CREATE_PAGE_MASTER_VALUATION_TYPE = `${ROUTE_MASTER_VALUATION_TYPE_PAGE}/create`;
export const EDIT_PAGE_MASTER_VALUATION_TYPE = `${ROUTE_MASTER_VALUATION_TYPE_PAGE}/update`;
export const DETAIL_PAGE_MASTER_VALUATION_TYPE = `${ROUTE_MASTER_VALUATION_TYPE_PAGE}/detail`;
