const ROUTE_MASTER_COST_CENTER_PAGE = '/master/cost-center';

export const LIST_PAGE_MASTER_COST_CENTER = `${ROUTE_MASTER_COST_CENTER_PAGE}`;
export const CREATE_PAGE_MASTER_COST_CENTER = `${ROUTE_MASTER_COST_CENTER_PAGE}/create`;
export const EDIT_PAGE_MASTER_COST_CENTER = `${ROUTE_MASTER_COST_CENTER_PAGE}/update`;
export const DETAIL_PAGE_MASTER_COST_CENTER = `${ROUTE_MASTER_COST_CENTER_PAGE}/detail`;
