import { GridColDef } from '@mui/x-data-grid';

export const columns: GridColDef[] = [
  { field: 'main_asset_number', headerName: 'Main Asset Number', width: 200, filterable: true },
  { field: 'asset_subnumber', headerName: 'Asset Subnumber', width: 200, filterable: true },
  { field: 'order_number', headerName: 'Order Number', width: 200, filterable: true },
  {
    field: 'purchasing_document_number',
    headerName: 'Purchasing Document Number',
    width: 200,
    filterable: true,
  },
  {
    field: 'item_number_of_purchasing_document',
    headerName: 'Item Number of Purchasing Document',
    width: 200,
    filterable: true,
  },
  { field: 'cost_center', headerName: 'Cost Center', width: 200, filterable: true },
  {
    field: 'purchasing_document_date',
    headerName: 'Purchasing Document Date',
    width: 200,
    filterable: true,
  },
  {
    field: 'purchasing_document_type',
    headerName: 'Purchasing Document Type',
    width: 200,
    filterable: true,
  },
  { field: 'company_code', headerName: 'Company Code', width: 200, filterable: true },
  { field: 'purchasing_group', headerName: 'Purchasing Group', width: 200, filterable: true },
  {
    field: 'purchasing_organization',
    headerName: 'Purchasing Organization',
    width: 200,
    filterable: true,
  },
  { field: 'incoterms_part1', headerName: 'Incoterms Part 1', width: 200, filterable: true },
  { field: 'incoterms_part2', headerName: 'Incoterms Part 2', width: 200, filterable: true },
  {
    field: 'vendor_account_number',
    headerName: 'Vendor Account Number',
    width: 200,
    filterable: true,
  },
  { field: 'currency_key', headerName: 'Currency Key', width: 200, filterable: true },
  {
    field: 'terms_of_payment_key',
    headerName: 'Terms of Payment Key',
    width: 200,
    filterable: true,
  },
  { field: 'requisitioner_name', headerName: 'Requisitioner Name', width: 200, filterable: true },
  {
    field: 'purchase_requisition_number',
    headerName: 'Purchase Requisition Number',
    width: 200,
    filterable: true,
  },
  {
    field: 'requirement_tracking_number',
    headerName: 'Requirement Tracking Number',
    width: 200,
    filterable: true,
  },
  {
    field: 'item_number_of_purchase_requisition',
    headerName: 'Item Number of Purchase Requisition',
    width: 200,
    filterable: true,
  },
  {
    field: 'delivery_completed_indicator',
    headerName: 'Delivery Completed Indicator',
    width: 200,
    filterable: true,
  },
  {
    field: 'final_invoice_indicator',
    headerName: 'Final Invoice Indicator',
    width: 200,
    filterable: true,
  },
  {
    field: 'account_assignment_category',
    headerName: 'Account Assignment Category',
    width: 200,
    filterable: true,
  },
  { field: 'storage_location', headerName: 'Storage Location', width: 200, filterable: true },
  { field: 'deletion_indicator', headerName: 'Deletion Indicator', width: 200, filterable: true },
  { field: 'material_group', headerName: 'Material Group', width: 200, filterable: true },
  { field: 'material_number', headerName: 'Material Number', width: 200, filterable: true },
  { field: 'po_unit_of_measure', headerName: 'PO Unit of Measure', width: 200, filterable: true },
  { field: 'po_quantity', headerName: 'PO Quantity', width: 200, filterable: true },
  { field: 'tax_code', headerName: 'Tax Code', width: 200, filterable: true },
  { field: 'net_price', headerName: 'Net Price', width: 200, filterable: true },
  { field: 'item_category', headerName: 'Item Category', width: 200, filterable: true },
  {
    field: 'invoice_receipt_indicator',
    headerName: 'Invoice Receipt Indicator',
    width: 200,
    filterable: true,
  },
  { field: 'short_text', headerName: 'Short Text', width: 200, filterable: true },
  {
    field: 'gr_based_invoice_verification',
    headerName: 'GR Based Invoice Verification',
    width: 200,
    filterable: true,
  },
  {
    field: 'goods_receipt_indicator',
    headerName: 'Goods Receipt Indicator',
    width: 200,
    filterable: true,
  },
  { field: 'plant', headerName: 'Plant', width: 200, filterable: true },
  { field: 'status', headerName: 'Status', width: 200, filterable: true },
  { field: 'code', headerName: 'Code', width: 200, filterable: true },
  { field: 'message', headerName: 'Message', width: 200, filterable: true },
  { field: 'attachment_link', headerName: 'Attachment Link', width: 200, filterable: true },
];
