const ROUTE_MASTER_PURCHASING_GROUP = '/api/master-pr/purchasing-group';

export const GET_MASTER_PURCHASING_GROUP = `${ROUTE_MASTER_PURCHASING_GROUP}/list`;
export const CREATE_MASTER_PURCHASING_GROUP = `${ROUTE_MASTER_PURCHASING_GROUP}/create`;
export const EDIT_MASTER_PURCHASING_GROUP = `${ROUTE_MASTER_PURCHASING_GROUP}/update`;
export const DETAIL_MASTER_PURCHASING_GROUP = (id: any) =>
  `${ROUTE_MASTER_PURCHASING_GROUP}/detail/${id}`;
export const DELET_MASTER_PURCHASING_GROUP = `${ROUTE_MASTER_PURCHASING_GROUP}/delete`;
