const ROUTE_MASTER_PURCHASING_GROUP_PAGE = '/master-pr/purchasing-group';

export const LIST_PAGE_MASTER_PURCHASING_GROUP = `${ROUTE_MASTER_PURCHASING_GROUP_PAGE}`;
export const CREATE_PAGE_MASTER_PURCHASING_GROUP = `${ROUTE_MASTER_PURCHASING_GROUP_PAGE}/create`;
export const EDIT_PAGE_MASTER_PURCHASING_GROUP = `${ROUTE_MASTER_PURCHASING_GROUP_PAGE}/update`;
export const DETAIL_PAGE_MASTER_PURCHASING_GROUP = `${ROUTE_MASTER_PURCHASING_GROUP_PAGE}/detail`;
