const ROUTE_SETTING_APPROVAL_PAGE = '/approval/setting';

export const LIST_PAGE_SETTING_APPROVAL = `${ROUTE_SETTING_APPROVAL_PAGE}`;
export const CREATE_PAGE_SETTING_APPROVAL = `${ROUTE_SETTING_APPROVAL_PAGE}/create`;
export const EDIT_PAGE_SETTING_APPROVAL = `${ROUTE_SETTING_APPROVAL_PAGE}/update`;
export const DETAIL_PAGE_SETTING_APPROVAL = `${ROUTE_SETTING_APPROVAL_PAGE}/detail`;
