const ROUTE_MASTER_CURRENCY_PAGE = '/master-pr/currency';

export const LIST_PAGE_MASTER_CURRENCY = `${ROUTE_MASTER_CURRENCY_PAGE}`;
export const CREATE_PAGE_MASTER_CURRENCY = `${ROUTE_MASTER_CURRENCY_PAGE}/create`;
export const EDIT_PAGE_MASTER_CURRENCY = `${ROUTE_MASTER_CURRENCY_PAGE}/update`;
export const DETAIL_PAGE_MASTER_CURRENCY = `${ROUTE_MASTER_CURRENCY_PAGE}/detail`;
