const ROUTE_APPROVAL_CONDITIONAL_USER = '/api/approval/approval-conditional-user';

export const GET_APPROVAL_CONDITIONAL_USER = `${ROUTE_APPROVAL_CONDITIONAL_USER}/list`;
export const CREATE_APPROVAL_CONDITIONAL_USER = `${ROUTE_APPROVAL_CONDITIONAL_USER}/create`;
export const EDIT_APPROVAL_CONDITIONAL_USER = `${ROUTE_APPROVAL_CONDITIONAL_USER}/update`;
export const DETAIL_APPROVAL_CONDITIONAL_USER = (id: any) =>
  `${ROUTE_APPROVAL_CONDITIONAL_USER}/detail/${id}`;
export const DELET_APPROVAL_CONDITIONAL_USER = `${ROUTE_APPROVAL_CONDITIONAL_USER}/delete`;
export const LIST_APPROVAL_CONDITIONAL_USER_DROPDOWN = (id: any) =>
  `${ROUTE_APPROVAL_CONDITIONAL_USER}/get-user-dropdown/${id}`;

export const CREATE_APPROVAL_CONDITIONAL_USER_DROPDOWN = `${ROUTE_APPROVAL_CONDITIONAL_USER}/store-user`;
