const ROUTE_APPROVAL_CONDITIONAL_USER_PAGE = '/approval/approval-conditional-user';

export const LIST_PAGE_APPROVAL_CONDITIONAL_USER = `${ROUTE_APPROVAL_CONDITIONAL_USER_PAGE}`;
export const CREATE_PAGE_APPROVAL_CONDITIONAL_USER = `${ROUTE_APPROVAL_CONDITIONAL_USER_PAGE}/create`;
export const EDIT_PAGE_APPROVAL_CONDITIONAL_USER = `${ROUTE_APPROVAL_CONDITIONAL_USER_PAGE}/update`;
export const DETAIL_PAGE_APPROVAL_CONDITIONAL_USER = `${ROUTE_APPROVAL_CONDITIONAL_USER_PAGE}/detail`;
