import { FormFieldModel } from '@/interfaces/form/formWrapper';
import ItemForm from './itemForm';
import CheckApproval from './checkApproval';
import CashAdvance from './CashAdvance';
import Attachment from './attachment';

export const formModel: Array<FormFieldModel<any>> = [
  {
    type: 'select',
    name: 'user_id',
    label: 'Request For',
    required: true,
    options: [],
    style: {
      width: '63.3rem',
    },
  },
  {
    type: 'select',
    name: 'document_type',
    label: 'Document Type',
    required: true,
    options: [],
    style: {
      width: '63.3rem',
    },
  },
  {
    type: 'select',
    name: 'purchasing_groups',
    label: 'Purchasing Group',
    required: true,
    options: [],
    style: {
      width: '63.3rem',
    },
  },
  {
    type: 'input',
    name: 'delivery_date',
    label: 'Delivery Date',
    required: true,
    texttype: 'date',
    placeholder: 'enter your date item delivery',
  },
  {
    type: 'select',
    name: 'storage_locations',
    label: 'Recieving Location',
    placeholder: 'Select Location',
    required: false,
    options: [],
    style: {
      width: '63.3rem',
    },
  },
  {
    disabled: false,
    maxLength: 100,
    type: 'textarea',
    name: 'entertainment.header_not',
    label: 'Header Note',
    placeholder: 'Header Note',
    style: {
      width: '63.5rem',
    },
  },
  {
    conditional: true,
    valueConditional: 'ZENT',
    parameterConditional: 'document_type',
    required: true,
    type: 'input',
    name: 'entertainment.tanggal',
    texttype: 'date',
    label: ' Entertainment Date',
    placeholder: ' Entertainment Date',
    style: {
      width: '63.5rem',
    },
  },
  {
    conditional: true,
    valueConditional: 'ZENT',
    parameterConditional: 'document_type',
    type: 'input',
    required: true,
    name: 'entertainment.tempat',
    label: 'Entertainment Location',
    placeholder: 'Entertainment Location',
    style: {
      width: '63.5rem',
    },
  },
  {
    conditional: true,
    valueConditional: 'ZENT',
    parameterConditional: 'document_type',
    type: 'input',
    required: true,
    name: 'entertainment.alamat',
    label: 'Entertainment Address',
    placeholder: 'Entertainment Address',
    style: {
      width: '63.5rem',
    },
  },
  {
    conditional: true,
    valueConditional: 'ZENT',
    parameterConditional: 'document_type',
    type: 'input',
    required: true,
    name: 'entertainment.jenis',
    label: 'Type of Entertainment',
    placeholder: 'Type of Entertainment',
    style: {
      width: '63.5rem',
    },
  },
  {
    conditional: true,
    valueConditional: 'ZENT',
    parameterConditional: 'document_type',
    type: 'input',
    name: 'entertainment.nama_perusahaan',
    required: true,
    label: 'Company Name',
    placeholder: 'Company Name entertainments',
    style: {
      width: '63.5rem',
    },
  },

  {
    conditional: true,
    valueConditional: 'ZENT',
    parameterConditional: 'document_type',
    type: 'input',
    required: true,
    name: 'entertainment.nama',
    label: 'Entertained Name',
    placeholder: 'Entertained Name',
    style: {
      width: '63.5rem',
    },
  },
  {
    conditional: true,
    valueConditional: 'ZENT',
    parameterConditional: 'document_type',
    type: 'input',
    required: true,
    name: 'entertainment.posisi',
    label: 'Entertained Position',
    placeholder: 'Entertained Position',
    style: {
      width: '63.5rem',
    },
  },
  {
    conditional: true,
    valueConditional: 'ZENT',
    parameterConditional: 'document_type',
    type: 'input',
    name: 'entertainment.jenis_usaha',
    required: true,

    label: 'type of Bussines',
    placeholder: 'Type of Bussines public/private',
    note: 'Please Add Kind of Business Type: Private / Public',
    style: {
      width: '63.5rem',
    },
  },
  {
    conditional: true,
    valueConditional: 'ZENT',
    parameterConditional: 'document_type',
    required: true,
    type: 'input',
    name: 'entertainment.jenis_kegiatan',
    label: 'Type of Activity',
    placeholder: 'Type of Activity',
    style: {
      width: '63.5rem',
    },
  },
  {
    type: 'input',
    name: 'total_vendor',
    label: 'Total Vendor Comparison',
    required: true,
    texttype: 'number',
    placeholder: 'enter your Total Vendor Comparison',
  },
  {
    type: 'select',
    name: 'currency_from',
    label: 'Currency',
    required: true,
    options: [],
    style: {
      width: '63.3rem',
    },
  },
  //   {
  //     type: 'switch',
  //     name: 'is_conversion_currency',
  //     label: 'Currency Conversion',
  //   },
  //   {
  //     conditional: true,
  //     valueConditional: true,
  //     parameterConditional: 'is_conversion_currency',
  //     type: 'select',
  //     name: 'currency_to',
  //     label: 'Currency Conversion',
  //     options: [],
  //     required: true,
  //     style: {
  //       width: '63.5rem',
  //     },
  //   },
  {
    fieldCustome: true,
    fieldCustomeValue: <Attachment isDisabled={false} />,
  },
  {
    fieldCustome: true,
    fieldCustomeValue: <ItemForm disable={false} />,
  },
  {
    fieldCustome: true,
    fieldCustomeValue: <CashAdvance disable={false} />,
  },
  {
    fieldCustome: true,
    fieldCustomeValue: <CheckApproval isDisabled={false} />,
  },
];

export const formModelEdit: Array<FormFieldModel<any>> = [
  {
    disabled: true,
    type: 'select',
    name: 'user_id',
    label: 'Request For',
    required: true,
    options: [],
    style: {
      width: '63.3rem',
    },
  },
  {
    disabled: true,
    type: 'select',
    name: 'document_type',
    label: 'Document Type',
    required: true,
    options: [],
    style: {
      width: '63.3rem',
    },
  },
  {
    disabled: true,
    type: 'select',
    name: 'purchasing_groups',
    label: 'Purchasing Group',
    required: true,
    options: [],
    style: {
      width: '63.3rem',
    },
  },
  {
    disabled: true,
    type: 'input',
    name: 'delivery_date',
    label: 'Delivery Date',
    required: true,
    texttype: 'date',
    placeholder: 'enter your date item delivery',
  },
  {
    disabled: true,
    type: 'select',
    name: 'storage_locations',
    label: 'Recieving Location',
    required: false,
    options: [],
    style: {
      width: '63.3rem',
    },
  },

  {
    disabled: true,
    maxLength: 100,
    type: 'textarea',
    name: 'entertainment.header_not',
    label: 'Header Note',
    placeholder: 'Header Note',
    style: {
      width: '63.5rem',
    },
  },
  {
    disabled: true,
    conditional: true,
    valueConditional: 'ZENT',
    parameterConditional: 'document_type',
    type: 'input',
    name: 'entertainment.tanggal',
    texttype: 'date',
    label: ' Entertainment Date',
    placeholder: ' Entertainment Date',
    style: {
      width: '63.5rem',
    },
  },
  {
    disabled: true,
    conditional: true,
    valueConditional: 'ZENT',
    parameterConditional: 'document_type',
    type: 'input',
    name: 'entertainment.tempat',
    label: 'Entertainment Location',
    placeholder: 'Entertainment Location',
    style: {
      width: '63.5rem',
    },
  },
  {
    disabled: true,

    conditional: true,
    valueConditional: 'ZENT',
    parameterConditional: 'document_type',
    type: 'input',
    name: 'entertainment.alamat',
    label: 'Entertainment Address',
    placeholder: 'Entertainment Address',
    style: {
      width: '63.5rem',
    },
  },
  {
    disabled: true,
    conditional: true,
    valueConditional: 'ZENT',
    parameterConditional: 'document_type',
    type: 'input',
    name: 'entertainment.jenis',
    label: 'Type of Entertainment',
    placeholder: 'Type of Entertainment',
    style: {
      width: '63.5rem',
    },
  },
  {
    disabled: true,
    conditional: true,
    valueConditional: 'ZENT',
    parameterConditional: 'document_type',
    type: 'input',
    name: 'entertainment.nama_perusahaan',
    label: 'Company Name',
    placeholder: 'Company Name entertainments',
    style: {
      width: '63.5rem',
    },
  },

  {
    disabled: true,
    conditional: true,
    valueConditional: 'ZENT',
    parameterConditional: 'document_type',
    type: 'input',
    name: 'entertainment.nama',
    label: 'Entertained Name',
    placeholder: 'Entertained Name',
    style: {
      width: '63.5rem',
    },
  },
  {
    disabled: true,
    conditional: true,
    valueConditional: 'ZENT',
    parameterConditional: 'document_type',
    type: 'input',
    name: 'entertainment.posisi',
    label: 'Entertained Position',
    placeholder: 'Entertained Position',
    style: {
      width: '63.5rem',
    },
  },
  {
    disabled: true,
    conditional: true,
    valueConditional: 'ZENT',
    parameterConditional: 'document_type',
    type: 'input',
    name: 'entertainment.jenis_usaha',
    label: 'jenis usaha entertainments',
    placeholder: 'Type of Bussines public/private',
    note: 'Please Add Kind of Business Type: Private / Public',
    style: {
      width: '63.5rem',
    },
  },
  {
    disabled: true,
    conditional: true,
    valueConditional: 'ZENT',
    parameterConditional: 'document_type',
    type: 'input',
    name: 'entertainment.jenis_kegiatan',
    label: 'Type of Activity',
    placeholder: 'Type of Activity',
    style: {
      width: '63.5rem',
    },
  },
  {
    disabled: true,
    type: 'input',
    name: 'total_vendor',
    label: 'Total Vendor Comparison',
    required: true,
    texttype: 'number',
    placeholder: 'enter your Total Vendor Comparison',
  },
  {
    fieldCustome: true,
    fieldCustomeValue: <Attachment isDisabled={false} />,
  },
  {
    fieldCustome: true,
    fieldCustomeValue: <ItemForm disable={true} />,
  },
  {
    fieldCustome: true,
    fieldCustomeValue: <CashAdvance disable={true} />,
  },
];
