import { FormFieldModel } from '@/interfaces/form/formWrapper';

export const formModel: Array<FormFieldModel<any>> = [
  {
    type: 'input',
    name: 'intem_number',
    label: 'Item Number',
    placeholder: 'Enter your item number',
    required: false,
  },
  {
    type: 'input',
    name: 'deletion_indicator',
    label: 'Deletion Indicator',
    placeholder: 'Enter your deletion indicator',
    required: false,
  },
  {
    type: 'input',
    name: 'request_date',
    label: 'Request Date',
    placeholder: 'Enter your request date',
    texttype: 'date',
    required: false,
  },
  {
    type: 'input',
    name: 'requirement_tracking_number',
    label: 'Tracking Number',
    placeholder: 'Enter your tracking number',
    required: false,
  },
  {
    type: 'select',
    name: 'document_type_id',
    label: 'Document Type',
    required: false,
    options: [],
    style: {
      width: '60rem',
    },
  },
  {
    type: 'select',
    name: 'valuation_type_id',
    label: 'Valuation Type',
    required: false,
    options: [],
    style: {
      width: '60rem',
    },
  },
  {
    type: 'input',
    name: 'purchase_requisition_closed',
    label: 'Requisition Closed',
    placeholder: 'Enter your requisition closed',
    required: false,
  },
  {
    type: 'select',
    name: 'purchasing_group_id',
    label: 'Purchasing Group',
    required: false,
    options: [],
    style: {
      width: '60rem',
    },
  },
  {
    type: 'input',
    name: 'purchasing_organization',
    label: 'Purchasing Organization',
    placeholder: 'Enter your purchasing organization',
    required: false,
  },
  {
    type: 'select',
    name: 'account_assignment_category_id',
    label: 'Account Assignment Category',
    required: false,
    options: [],
    style: {
      width: '60rem',
    },
  },
  {
    type: 'input',
    name: 'item_delivery_date',
    label: 'Item Delivery Date',
    placeholder: 'Enter your item delivery date',
    texttype: 'date',
    required: false,
  },
  {
    type: 'select',
    name: 'storage_location_id',
    label: 'Storage Location',
    required: false,
    options: [],
    style: {
      width: '60rem',
    },
  },
  {
    type: 'input',
    name: 'desired_vendor',
    label: 'Desired Vendor',
    placeholder: 'Enter your desired vendor',
    required: false,
  },
  {
    type: 'select',
    name: 'material_group_id',
    label: 'Material Group',
    required: false,
    options: [],
    style: {
      width: '60rem',
    },
  },
  {
    type: 'input',
    name: 'material_number',
    label: 'Material Number',
    placeholder: 'Enter your material number',
    required: false,
  },
  {
    type: 'input',
    name: 'purchase_requisition_unit',
    label: 'Purchase requisition unit',
    placeholder: 'Enter your Purchase requisition unit',
    required: false,
  },
  {
    type: 'input',
    name: 'purchase_requisition_quantity',
    label: 'Purchase requisition quantity',
    placeholder: 'Enter your Purchase requisition quantity',
    required: false,
  },
  {
    type: 'input',
    name: 'pajak_id',
    label: 'Tax on sales',
    placeholder: 'Enter your tax on sales',
    required: false,
  },
  {
    type: 'input',
    name: 'item_category',
    label: 'Item Category',
    placeholder: 'Enter your item category',
    required: false,
  },
  {
    type: 'select',
    name: 'plant',
    label: 'Plant',
    required: false,
    options: [],
    style: {
      width: '60rem',
    },
  },
];
