const ROUTE_MASTER_STORAGE_LOCATION = '/api/master-pr/storage-location';

export const GET_MASTER_STORAGE_LOCATION = `${ROUTE_MASTER_STORAGE_LOCATION}/list`;
export const CREATE_MASTER_STORAGE_LOCATION = `${ROUTE_MASTER_STORAGE_LOCATION}/create`;
export const EDIT_MASTER_STORAGE_LOCATION = `${ROUTE_MASTER_STORAGE_LOCATION}/update`;
export const DETAIL_MASTER_STORAGE_LOCATION = (id: any) =>
  `${ROUTE_MASTER_STORAGE_LOCATION}/detail/${id}`;
export const DELET_MASTER_STORAGE_LOCATION = `${ROUTE_MASTER_STORAGE_LOCATION}/delete`;
