const ROUTE_MASTER_STORAGE_LOCATION_PAGE = '/master-pr/storage-location';

export const LIST_PAGE_MASTER_STORAGE_LOCATION = `${ROUTE_MASTER_STORAGE_LOCATION_PAGE}`;
export const CREATE_PAGE_MASTER_STORAGE_LOCATION = `${ROUTE_MASTER_STORAGE_LOCATION_PAGE}/create`;
export const EDIT_PAGE_MASTER_STORAGE_LOCATION = `${ROUTE_MASTER_STORAGE_LOCATION_PAGE}/update`;
export const DETAIL_PAGE_MASTER_STORAGE_LOCATION = `${ROUTE_MASTER_STORAGE_LOCATION_PAGE}/detail`;
