const ROUTE_MASTER_MATERIAL_GROUP = '/api/master-pr/material-group';

export const GET_MASTER_MATERIAL_GROUP = `${ROUTE_MASTER_MATERIAL_GROUP}/list`;
export const CREATE_MASTER_MATERIAL_GROUP = `${ROUTE_MASTER_MATERIAL_GROUP}/create`;
export const EDIT_MASTER_MATERIAL_GROUP = `${ROUTE_MASTER_MATERIAL_GROUP}/update`;
export const DETAIL_MASTER_MATERIAL_GROUP = (id: any) =>
  `${ROUTE_MASTER_MATERIAL_GROUP}/detail/${id}`;
export const DELET_MASTER_MATERIAL_GROUP = `${ROUTE_MASTER_MATERIAL_GROUP}/delete`;
