const ROUTE_MASTER_DEPARTMENT_PAGE = '/master/department';

export const LIST_PAGE_MASTER_DEPARTMENT = `${ROUTE_MASTER_DEPARTMENT_PAGE}`;
export const CREATE_PAGE_MASTER_DEPARTMENT = `${ROUTE_MASTER_DEPARTMENT_PAGE}/create`;
export const EDIT_PAGE_MASTER_DEPARTMENT = `${ROUTE_MASTER_DEPARTMENT_PAGE}/update`;
export const DETAIL_PAGE_MASTER_DEPARTMENT = `${ROUTE_MASTER_DEPARTMENT_PAGE}/detail`;
