const ROUTE_TRACKING_NUMBER_AUTO_PAGE = '/approval/tracking-number-auto';

export const LIST_PAGE_TRACKING_NUMBER_AUTO = `${ROUTE_TRACKING_NUMBER_AUTO_PAGE}`;
export const CREATE_PAGE_TRACKING_NUMBER_AUTO = `${ROUTE_TRACKING_NUMBER_AUTO_PAGE}/create`;
export const EDIT_PAGE_TRACKING_NUMBER_AUTO = `${ROUTE_TRACKING_NUMBER_AUTO_PAGE}/update`;
export const DETAIL_PAGE_TRACKING_NUMBER_AUTO = `${ROUTE_TRACKING_NUMBER_AUTO_PAGE}/detail`;
