const ROUTE_TRACKING_NUMBER_CHOOSE = '/api/approval/tracking-number-choose';

export const GET_TRACKING_NUMBER_CHOOSE = `${ROUTE_TRACKING_NUMBER_CHOOSE}/list`;
export const CREATE_TRACKING_NUMBER_CHOOSE = `${ROUTE_TRACKING_NUMBER_CHOOSE}/create`;
export const EDIT_TRACKING_NUMBER_CHOOSE = `${ROUTE_TRACKING_NUMBER_CHOOSE}/update`;
export const DETAIL_TRACKING_NUMBER_CHOOSE = (id: any) =>
  `${ROUTE_TRACKING_NUMBER_CHOOSE}/detail/${id}`;
export const DELET_TRACKING_NUMBER_CHOOSE = `${ROUTE_TRACKING_NUMBER_CHOOSE}/delete`;
