const ROUTE_TRACKING_NUMBER_CHOOSE_PAGE = '/approval/tracking-number-choose';

export const LIST_PAGE_TRACKING_NUMBER_CHOOSE = `${ROUTE_TRACKING_NUMBER_CHOOSE_PAGE}`;
export const CREATE_PAGE_TRACKING_NUMBER_CHOOSE = `${ROUTE_TRACKING_NUMBER_CHOOSE_PAGE}/create`;
export const EDIT_PAGE_TRACKING_NUMBER_CHOOSE = `${ROUTE_TRACKING_NUMBER_CHOOSE_PAGE}/update`;
export const DETAIL_PAGE_TRACKING_NUMBER_CHOOSE = `${ROUTE_TRACKING_NUMBER_CHOOSE_PAGE}/detail`;
