const ROUTE_SETTING_APPROVAL_PR_PAGE = '/approval/pr';

export const LIST_PAGE_SETTING_APPROVAL_PR = `${ROUTE_SETTING_APPROVAL_PR_PAGE}`;
export const CREATE_PAGE_SETTING_APPROVAL_PR = `${ROUTE_SETTING_APPROVAL_PR_PAGE}/create`;
export const EDIT_PAGE_SETTING_APPROVAL_PR = `${ROUTE_SETTING_APPROVAL_PR_PAGE}/update`;
export const DETAIL_PAGE_SETTING_APPROVAL_PR = `${ROUTE_SETTING_APPROVAL_PR_PAGE}/detail`;
