const ROUTE_MASTER_TRACKING_NUMBER = '/api/master/tracking-number';

export const GET_MASTER_TRACKING_NUMBER = `${ROUTE_MASTER_TRACKING_NUMBER}/list`;
export const CREATE_MASTER_TRACKING_NUMBER = `${ROUTE_MASTER_TRACKING_NUMBER}/create`;
export const EDIT_MASTER_TRACKING_NUMBER = `${ROUTE_MASTER_TRACKING_NUMBER}/update`;
export const DETAIL_MASTER_TRACKING_NUMBER = (id: any) =>
  `${ROUTE_MASTER_TRACKING_NUMBER}/detail/${id}`;
export const DELET_MASTER_TRACKING_NUMBER = `${ROUTE_MASTER_TRACKING_NUMBER}/delete`;
