const ROUTE_MASTER_TRACKING_NUMBER_PAGE = '/master/tracking-number';

export const LIST_PAGE_MASTER_TRACKING_NUMBER = `${ROUTE_MASTER_TRACKING_NUMBER_PAGE}`;
export const CREATE_PAGE_MASTER_TRACKING_NUMBER = `${ROUTE_MASTER_TRACKING_NUMBER_PAGE}/create`;
export const EDIT_PAGE_MASTER_TRACKING_NUMBER = `${ROUTE_MASTER_TRACKING_NUMBER_PAGE}/update`;
export const DETAIL_PAGE_MASTER_TRACKING_NUMBER = `${ROUTE_MASTER_TRACKING_NUMBER_PAGE}/detail`;
